---
- hosts: webservers
  become: True
  tasks: 
    - name : install apache2
      apt:
        name: "httpd"
        state: "present"
    - name: start apache2
      service:
        name: httpd
        state: present
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: present
